controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01

panda_hand_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    open_loop_control: false

joint_state_broadcaster:
  ros__parameters: {}
